#' Generate a leaflet map of the UK
#'
#' Generate a leaflet map of the UK with polygons for each LAD region filled
#' by their statistics.
#'
#' @param mapData The spatial data.
#' @param fill The data which should be used to fill the map polygons. Defaults
#'   to \code{NULL} in the event a statistics hasn't been provided.
#' @param bounds The boundaries of the map; generated by \code{\link[sp]{bbox}}.
#'
#' @author Nathan Eastwood
#'
#' @import leaflet
#' @export
leafMap <- function(mapData, fill = NULL, bounds) {

  # Create the plot
  map <- leaflet() %>%
    setView(
      mean(bounds[1, ]),
      mean(bounds[2, ]),
      zoom = 5
    ) %>%
    addProviderTiles(
      "CartoDB.Positron",
      options = providerTileOptions(minZoom = 4, maxZoom = 8)
    )

  # If a specific statistic is selected, generate the polygons layer for it
  if (!is.null(fill)) {
    # Generate the popup details
    details <- paste0(
      "<strong>LAD: </strong>",
      mapData@data$lad15nm,
      "<br><strong>", fill, ": </strong>",
      mapData@data[, fill]
    )

    # Generate a colour palette
    pal <- if (length(table(mapData@data[, fill])) == 4) {
      domain_min <- min(mapData@data[, fill], na.rm = TRUE)
      domain_max <- max(mapData@data[, fill], na.rm = TRUE)
      colorFactor("Greens", factor(mapData@data[, fill]))
    } else {
      domain_min <- min(roundDown(mapData@data[, fill]), na.rm = TRUE)
      domain_max <- max(roundUp(mapData@data[, fill]), na.rm = TRUE)
      colorNumeric("Greens", domain = domain_min:domain_max)
    }

    # Add the polygons
    map <-
      map %>%
      addPolygons(
        data = mapData,
        weight = 1,
        fillColor = pal(mapData@data[, fill]),
        fillOpacity = 0.8,
        color = "#BDBDC3",
        popup = details,
        layerId = mapData$lad15cd
      )
    if (length(table(mapData@data[, fill])) == 4) {
      map <-
        map %>%
        addLegend(pal = pal, values = mapData@data[, fill])
    } else {
      map <-
        map %>%
        addLegend(pal = pal, values = mapData@data[, fill],
                  labFormat = labelFormat(suffix = "%"))
    }
  }
  map
}
